# SPDX-FileCopyrightText: Copyright 2026 Daniel Balparda <balparda@github.com>
# SPDX-License-Identifier: Apache-2.0

repos:

  - repo: local

    hooks:

      # Run the linter
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        language: system
        types: [python]
        pass_filenames: false

      # Run the formatter
      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format --check
        language: system
        types: [python]
        pass_filenames: false

      # Run the type checker using local mypy with all project stubs
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        args: [src]
        pass_filenames: false
