# SPDX-FileCopyrightText: Copyright 2026 Daniel Balparda <balparda@github.com>
# SPDX-License-Identifier: Apache-2.0

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.14.13
    hooks:
      # Run the linter
      - id: ruff-check
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    # MyPI version
    rev: v1.19.1
    hooks:
      # Run the type checker
      - id: mypy
        additional_dependencies: [pytest==9.0, rich==14.2, typer==0.21]
